### ISSUE TITLE
How to develop locally, preferably in a REPL, (question rather than issue)

### ISSUE THREAD

**Issue by vikeri** [nervous-systems/cljs-lambda#20]
I was stoked to see this already existed. I have a couple of questions regarding implementation however, that to me were not entierly clear from the readme or blog posts. I would like to test the lambda function locally before deploying it. I got it working with basic examples in the tests. But when I started using callbacks (of external node-libs) in the lambda function the test finished before the callback came back, (Naturally, since the function returned while the callback was still firing).

Any details on when to use `lambda/succeed!` vs returning go channels, I understood that `async-lambda-fn` was supposed to be better than `wrap-lambda-fn`, but did not understand how?

Ultimately, any tips on how would I set up a good REPL-workflow with this?

**Comment by moea** [comment]
That could certainly be covered better in the readme.

Example function:

``` clojure
(def child-process (nodejs/require "child_process"))

(def ^:export sleep
  (lambda/wrap-lambda-fn
   (fn [seconds context]
     (.exec
      child-process
      (str "sleep " seconds)
      (fn [error stdout stderr]
        (if error
          (lambda/fail! context error)
          (lambda/succeed! context seconds)))))))
```

Test:

``` clojure
(deftest sleep
  (cljs.test/async
   done
   (go
     (let [context (mock-context)]
       (example/sleep 0.5 context)
       (let [[tag result] (<! (:cljs-lambda/resp-chan context))]
         (is (= tag :succeed))
         (is (= result 0.5))
         (done))))))
```

I think that w/ a mock context, `fail!` and `succeed!` could return the channel, rather than having it be looked up as above (in which case the test would be written identically to the below) --- I'll look into it.

`async-lambda-fn` isn't _better_, it's just likely to be more convenient if you're interacting with cljs written using core.async.  It works perfectly well for this kind of thing, though:

``` clojure
(def ^:export sleep
  (async-lambda-fn
   (fn [seconds context]
     (let [ch (async/chan)]
       (.exec
        child-process
        (str "sleep " seconds)
        (fn [error stdout stderr]
          (async/put! ch (or error seconds))
          (async/close! ch)))
       ch))))
```

Test:

``` clojure
(deftest sleep
  (cljs.test/async
   done
   (go
     (let [[tag result] (<! (example/sleep 0.5 (mock-context)))]
       (is (= tag :succeed))
       (is (= result 0.5))
       (done)))))
```

Let me know if you have thoughts about how best to adjust the readme - or this stuff could go on a wiki page or similar.  

About the repl: while developing, I usually run `lein doo node example-test` or whatever in a terminal, because the restart-on-save logic is helpful for this kind of thing (hanging functions, etc.).  I run a node repl via Cider for interactively working through any peripheral logic.  I tend to rely on the repl a little less when developing cljs code (Lambda or otherwise), because the experience isn't fantastic.

**Comment by vikeri** [comment]
Great, thanks! Got it working now :smile:
