### ISSUE TITLE
Question: growing number of lambda functions

### ISSUE THREAD

**Issue by zrzka** [nervous-systems/cljs-lambda#36]
Consider following scenario:
- one project
- 15 lambda functions (all functions are project related)
- number of lambda functions is growing

Upon build & deploy, one ZIP file is created for all lambda functions and this file is uploaded for every lambda function. This takes space and has performance implications when lambda is cold and it also needs slightly more memory.

What's your recommended approach / best practice to cope with this? Are you splitting lambda functions into groups and one project per group? Or project per lambda? Or did I miss something and I shouldn't worry? Can't get out of my head that I would like to process my lambda functions with `:advanced` optimization per lambda, so, there will be specific and small ZIP file per lambda function, but I don't like one lambda function = one project approach.

My ZIP file is 0.5MB now.

**Comment by moea** [comment]
There isn't intrinsic support for this in cljs-lambda (e.g. via per-function cljsbuild identifiers, which would definitely be possible, but a little complex).  One project per group is generally what I'm doing - the exception is one client with a fair number of fns - just over 15 - in a single project file, and a subset of them have some heavy static file dependencies, so we use a lein profile to conditionally include them, e.g. from project.clj:

`:profiles {:ffmpeg-fns {:cljs-lambda {:resource-dirs ["static"]}}}`

so at deploy time `lein with-profile +ffmpeg-fns cljs-lambda deploy gen-assets other-fn` or whatever will just deploy those functions with the `static/` directory which is otherwise not necessary.  The same approach could be used for `{:cljs-lambda {:cljs-build-id ...}}`, so that a different build is run under some custom profile - or just to adjust the source paths for a single build.

It's not ideal, but at least in our case, we should and can split at least some of the functions into a separate project - and given that there are already subproject tools for Lein (I haven't used them, and don't know how well they'd work in this scenario), I shied away from including full-blown support for totally different builds in cljs-lambda.

Let me know if any of that is helpful.

**Comment by zrzka** [comment]
Many thanks. That's just confirmed my findings and basically what I'm doing now.

P.S. Any timeframe for the next release with `nodejs4.3` runtime support (already merged into `master`)?

**Comment by moea** [comment]
I'll get to it this week, have been QA'ing it in the wild.  The version'll jump to 0.6.0 b/c I think the change may break some older versions of the AWS CLI.

**Comment by moea** [comment]
N.B. lein-cljs-lambda 0.6.0-SNAPSHOT is out there if you want to give it a try before a release.

**Comment by zrzka** [comment]
Ahh, missed it, thanks for info! Closing this issue for now.
