### ISSUE TITLE
Add option to disable npm install

### ISSUE THREAD

**Issue by honzabrecka** [nervous-systems/cljs-lambda#45]
Hi, would it be possible to add possibility to skip `npm install` step (https://github.com/nervous-systems/cljs-lambda/blob/master/plugin/src/leiningen/cljs_lambda.clj#L123)? The reason is that I want to use [yarn](https://yarnpkg.com/) instead of npm. What do you think?

**Comment by moea** [comment]
Would it work for you if there was a `:managed-deps` (or similar) option to build/deploy which didn't run npm install, and just included the current contents of node_modules in the zip file?  This'd mean you'd have to run whatever yarn command to fetch the dependencies if your package.json has changed since your last deploy, but that's not so bad, and could change if it made sense to integrate yarn support into the project in the future.

Aside from that would everything else be the same about the workflow (i.e. are all the project's js dependencies inside node_modules, etc.)?

**Comment by honzabrecka** [comment]
Thanks for your reply! Have `:managed-deps` option would be great.

Yes, yarn installs node dependencies to node_modules dir, so yes, everything remains the same.
