### ISSUE TITLE
Configure lambda functions with metadata instead of in project.clj

### ISSUE THREAD

**Issue by robinheghan** [nervous-systems/cljs-lambda#6]
Would it be possible to configure lambda functions using metadata instead of listing it in the project.clj? Something like this:

``` clj
(defn ^:export ^:aws-lambda sample [env context]
  "YAY")
```

**Comment by moea** [comment]
It would certainly be possible in principle.  The main problem is that this would require the plugin have runtime access to the project, for it to work in general case - we would have to scan all namespaces for vars which have some metadata key.  I think the only polite time to do that would be on Lambda - which is a problem for e.g. `lein cljs-lambda deploy` - that task needs to figure out what Lambda functions actually need to exist remotely - and I'm not sure how reasonable it is to load namespaces from the project to look around - but I haven't thought about the range of approaches.

Currently, the plugin knows very little about the actual program it's deploying - it generates an index.js which assumes that the function names provided in the project file refer to actually-existing functions - but if they don't, nobody's going to find out until the function has been deployed, and then remotely invoked. 

Anyway, I think this is shaky ground for a library/plugin - but you could probably implement something like this in your project - Since cljs-lambda doesn't have a task to generate zip files without trying to upload them, it might be easier to not use it.  Basically, you'd want your zip to expose a single JS or Clojurescript function, and you'd set this as the handler to be invoked by your different Lambda functions.  This guy would do some runtime dispatch - based, say, on the name of the Lambda function which was invoked - I'm assuming that exists on the context - you could upload the zip file as the source for all of your Lambda functions, and have something different happen at execution time.

I hope some of that made sense.

**Comment by robinheghan** [comment]
Makes perfect sense :)
