### ISSUE TITLE
Serverless template does not include doo

### ISSUE THREAD

**Issue by dpurrington** [nervous-systems/cljs-lambda#72]
Apologies if this is obvious, but I can't get doo to work with the Serverless project file. I see that the template is different. Should I not use doo with Serverless? Or is there some way of doing it that I don't understand? If the former, please advise on testing strategies. Thanks!

**Comment by moea** [comment]
@dpurrington I think `doo` requires cljsbuild, and the serverless template creates a project which instructs `cljs-lambda` to invoke the cljs compiler directly (which, in practice, isn't any different than using cljsbuild, it's just one fewer dep).  If you added cljsbuild & doo to your `:plugins` vector, and created a build in `:cljsbuild` with the same map/keys as your project file's`:cljs-lambda` -> `:compiler` guy - then you ought to be good to go.  If you have difficulty with that approach I can give it a go and send over a gist - let me know how you get on.

There's a tension between providing a template with the fewest number of dependencies, and one which requires the smallest amount of modification in order to be useful - the serverless template is super bare-bones - I think I'll merge the two templates and add `:doo` & `:serverless` options.

**Comment by dpurrington** [comment]
I got it to work. Thanks for the help. Now I'm having a more basic problem. When I use optimizations :none, I get the error that "goog is not defined." When using :simple, the error goes away.

I feel like the answer is somewhere in [here](https://github.com/clojure/clojurescript/wiki/Quick-Start#notes-on-optimization-settings) but I'm not grokking it.
