### ISSUE TITLE
Consider a lumo version

### ISSUE THREAD

**Issue by arichiardi** [nervous-systems/cljs-lambda#94]
Hello folks!

It would be really awesome to have something so that we could make `cljs-lambda` work in `lumo`.
Not only it would have faster startup but also the interactive REPL with `lumo` would be super easy to setup (compared to both nRepl and vanilla ClojureScript).

The problem that strikes me immediately is that there is a dependency on `core.async` that should be replaced by https://github.com/mfikes/andare. Also `promesa` could be replaced by vanilla Bluebird directly.

And....Yes...I see that would drastically change the project layout and it is probably worth a separate project.

In any case, thanks for your work on this, it is quite useful!

**Comment by JimLynchCodes** [comment]
It would be really nice to be able to call the main function that is created with "deflambda" right from the repl instead of having to deploy it to aws each time. Is this possible already? Is there something special you would need to do to be able to call it from lumo?

**Comment by moea** [comment]
[serverless-cljs-plugin](https://github.com/nervous-systems/serverless-cljs-plugin) supports Lumo - but let's set that aside, because you can call the functions in your project from a REPL, regardless of whether it's a lumo or jvm-compiled cljs project.  

That said, it makes more sense to do something like this:

```clj
(defn my-fn [event]
  ;; do something, return a promise
  ...)

(deflambda my-lambda-fn [event ctx]
  (my-fn event))
```

And just call `my-fn` from the repl, because it accepts maps, whereas `my-lambda-fn` wants javascript Objects it converts into maps, as that's what we get from the Lambda runtime.  There's utilities in cljs-lambda for constructing these for testing, but there isn't much of a reason to.

P.S. Note that unless you have a compelling reason to do otherwise, I would recommend using JVM compilation over Lumo, using Serverless to deploy, and using cljs-lambda, the runtime library, for utilities.  [Blog post here](https://nervous.io/clojurescript/lambda/2017/02/06/serverless-cljs/).  The AWS handling code in lein-cljs-lambda is perfectly fine, and functional, however serverless is much more general and ambitious in that regard.

**Comment by JimLynchCodes** [comment]
Hmm, I've been trying this for a while with no luck. What directory should I be in when I start lumo? for some reason my REPL cannot find the namespace. :(

**Comment by arichiardi** [comment]
I will create a sample project, but the root folder is the usual and you need `sls package` and the right conf in `serverless.yml` for it to work.

Which error do you get? 

I am going to close this issue because `lumo` support is there and I am using it every day.

Maybe you can open a new issue?

**Comment by JimLynchCodes** [comment]
sorry, what do you mean by "sls pacckage" and "the right conf"?

**Comment by arichiardi** [comment]
Sorry I have mixed up the projects a little, check this out: https://github.com/nervous-systems/serverless-cljs-plugin
